### ISSUE TITLE
support node 10 ?

### ISSUE THREAD

**Issue by ccbikai** [ota-meshi/postcss-styl#24]
I found node version must be "^8.10.0 || >=11.10.1" in package.json.

But I use node 10 `yarn add postcss-styl -D --ignore-engines`, It can work .

**Comment by ota-meshi** [comment]
Thank you for this problem.

I would like to support Node.js@10.
Please wait.

**Comment by ota-meshi** [comment]
@ccbikai I released v0.3.2!
Please let me know if there are other problems!
