### ISSUE TITLE
Add support for parsing @require

### ISSUE THREAD

**Issue by darrenswhite** [ota-meshi/postcss-styl#40]
\@import works fine but @require does not work. See https://stylus-lang.com/docs/import.html#require

**Comment by ota-meshi** [comment]
Thank you for this issue!

How do you use this parser?
I looking at the following testcase, the parses is working.

https://github.com/ota-meshi/postcss-styl/blob/master/tests/fixtures/%40require01/input.styl
https://github.com/ota-meshi/postcss-styl/blob/master/tests/fixtures/%40require01/parsed.json

**Comment by darrenswhite** [comment]
I was using it with this: https://github.com/ota-meshi/stylelint-plugin-stylus

**Comment by ota-meshi** [comment]
I don't know which version of `stylelint-plugin-stylus` you are using, but it seems to work with [DEMO].

If the latest version doesn't work, could you open an issue at `stylelint-plugin-stylus`? Also, could you share detailed information?

[DEMO]: https://ota-meshi.github.io/stylelint-plugin-stylus/playground/#eJyrVkrOT0lVslJyyMwtyC8qUVDX00/Lz9crLqnMUY/Ji8lzKEotLM0sSsWQ0EuMyVNQSM7PyS9SKEpNiclTqgUA/QUahQ==
